In [18]:
from glob import glob
from pathlib import Path
import json
import random
from collections import defaultdict
import pandas as pd

In [ ]:
fn_test = "../saves/reproduce/HGERE/gsap_rel_models/scibert/tersibcop/facencbiaf-seq512-mem400-iter3-layernorm+_attnself/ent400-rel400-lr2e-5-1e-4-bs18-ep10-eps1e-8/Hyper_scierc_scibert-42/pred_ent_pred_test.json"

In [ ]:
fn_test = "/home/ottowg/projects/gsap/gsap-rel-related/HGERE/saves/gsap/HGERE/scibert/tersibcop/facencbiaf-seq512-mem400-iter3-layernorm+_attnself/ent400-rel400-lr2e-5-1e-4-bs18-ep10-eps1e-8/hyper_gsap_scibert-43/pred_ent_pred_test.json"

In [ ]:
fn_test = glob("/home/ottowg/projects/gsap/gsap-rel-related/HGERE/saves/gsap/HGERE/scibert/tersibcop/facencbiaf-seq512-mem400-iter3-layernorm+_attnself/ent400-rel400-lr2e-5-1e-4-bs18-ep10-eps1e-8/*")
fn_test[3]

## Setting:
 * data version 2025-02-04
 * train only on not null examples
 *

In [29]:
fn_test = '/home/ottowg/projects/gsap/gsap-rel-related/HGERE/saves/gsap/HGERE/scibert/tersibcop/facencbiaf-seq512-mem400-iter3-layernorm+_attnself/ent400-rel400-lr2e-5-1e-4-bs18-ep10-eps1e-8/hyper_gsap_scibert-2025-02-04-43'
glob(fn_test + "/*")

['/home/ottowg/projects/gsap/gsap-rel-related/HGERE/saves/gsap/HGERE/scibert/tersibcop/facencbiaf-seq512-mem400-iter3-layernorm+_attnself/ent400-rel400-lr2e-5-1e-4-bs18-ep10-eps1e-8/hyper_gsap_scibert-2025-02-04-43/scripts',
 '/home/ottowg/projects/gsap/gsap-rel-related/HGERE/saves/gsap/HGERE/scibert/tersibcop/facencbiaf-seq512-mem400-iter3-layernorm+_attnself/ent400-rel400-lr2e-5-1e-4-bs18-ep10-eps1e-8/hyper_gsap_scibert-2025-02-04-43/all_spkogpu01.log',
 '/home/ottowg/projects/gsap/gsap-rel-related/HGERE/saves/gsap/HGERE/scibert/tersibcop/facencbiaf-seq512-mem400-iter3-layernorm+_attnself/ent400-rel400-lr2e-5-1e-4-bs18-ep10-eps1e-8/hyper_gsap_scibert-2025-02-04-43/args',
 '/home/ottowg/projects/gsap/gsap-rel-related/HGERE/saves/gsap/HGERE/scibert/tersibcop/facencbiaf-seq512-mem400-iter3-layernorm+_attnself/ent400-rel400-lr2e-5-1e-4-bs18-ep10-eps1e-8/hyper_gsap_scibert-2025-02-04-43/checkpoint-61680',
 '/home/ottowg/projects/gsap/gsap-rel-related/HGERE/saves/gsap/HGERE/scibert/tersibcop/facencbiaf-seq512-mem400-iter3-layernorm+_attnself/ent400-rel400-lr2e-5-1e-4-bs18-ep10-eps1e-8/hyper_gsap_scibert-2025-02-04-43/pred_ent_pred_test.json',
 '/home/ottowg/projects/gsap/gsap-rel-related/HGERE/saves/gsap/HGERE/scibert/tersibcop/facencbiaf-seq512-mem400-iter3-layernorm+_attnself/ent400-rel400-lr2e-5-1e-4-bs18-ep10-eps1e-8/hyper_gsap_scibert-2025-02-04-43/test_results.txt']

In [28]:
fn_params = fn_test + "/args/training_args.txt"
with(open(fn_params)) as f:
    params_raw = f.read()
    params = eval(params_raw)
    params = pd.Series(params)
cols_params = ['data_dir', 'model_type', 'model_name_or_path', 'output_dir',
       'ner_prediction_dir',
               'train_file', 'dev_file', 'test_file',
               #'config_name',
               #'tokenizer_name', 
               #'cache_dir',
               'num_train_epochs', 
       'max_seq_length', 
        #'do_train', 'do_eval', 'do_test',
       #'evaluate_during_training', 'do_lower_case',
       'per_gpu_train_batch_size',
       'per_gpu_eval_batch_size', 'gradient_accumulation_steps',
       'learning_rate', 'learning_rate_cls', 'weight_decay', 'adam_epsilon',
       'max_grad_norm', 'max_steps', 'warmup_steps',
       'logging_steps', 'save_steps', 'eval_epochs', 
               #'eval_all_checkpoints',
       #'no_cuda', 'overwrite_output_dir', 'overwrite_cache', 'seed', 'fp16',
       #'fp16_opt_level', 'local_rank', 'server_ip', 'server_port',
       #'save_total_limit',
               
       #'max_pair_length', 'alpha',
               'save_results', 
        #       'no_test',
       #'eval_logsoftmax', 'eval_softmax', 'shuffle', 'lminit', 'no_sym',
       #'att_left', 'att_right', 'use_ner_results', 'use_typemarker',
       #'eval_unidirect', 'nocross', 'warmup_ratio', 'eval_logits', 'ent_repr',
       #'uni_ent', 'ent_enc', 'pred_sub', 'ner_cls', 'rel_enc', 'ent_dim',
       #'rel_dim', 'rel_rank', 'rel_factorize', 'baseline', 'factor_type',
       #'mem_dim', 'iter', 'layernorm', 'layernorm_1st', 'attn_self',
       #'aggregate_type', 'aggregate_func', 'agg_with_self', 'fix_obj',
       #'edgetype', 'attn_scorer', 'attn_res', 'n_head', 'd_head',
       #'factor_encoder', 'iter1', 'hostname'
              ]
params.loc[cols_params][:40]

data_dir
model_type                                                                 hyper
model_name_or_path                    pretrained_models/scibert_scivocab_uncased
output_dir                     saves/gsap/HGERE/scibert/tersibcop/facencbiaf-...
ner_prediction_dir                             saves/gsap/pruned_ner/2025-02-04/
train_file                                          ent_pred_train_not_null.json
dev_file                                                       ent_pred_dev.json
test_file                                                     ent_pred_test.json
num_train_epochs                                                            10.0
max_seq_length                                                               512
per_gpu_train_batch_size                                                      18
per_gpu_eval_batch_size                                                       32
gradient_accumulation_steps                                                    1
learning_rate                                                            0.00002
learning_rate_cls                                                         0.0001
weight_decay                                                                 0.0
adam_epsilon                                                                 0.0
max_grad_norm                                                                1.0
max_steps                                                                     -1
warmup_steps                                                                  -1
logging_steps                                                                  5
save_steps                                                                  1000
eval_epochs                                                                    2
save_results                                                               False
dtype: object

In [31]:
fn_metrics = fn_test + "/test_results.txt"
with open(fn_metrics) as f:
    print(f.read())

--------------------------
Best result on dev ent_pred_dev.json
{'ner_p': 0.7159241288045876, 'ner_r': 0.7426784624771202, 'ner_f1': 0.7290559257318261, 'p': 0.3699158485273492, 'r': 0.40236460717009914, 'f1': 0.3854585312385824, 'p+': 0.3015427769985975, 'r+': 0.32799389778794813, 'f1_with_ner': 0.3142126415783705}
--------------------------
Test result of saves/gsap/pruned_ner/2025-02-04/ent_pred_train_not_null.json
{'ner_p': 0.9746661885375577, 'ner_r': 0.9611032531824611, 'ner_f1': 0.9678372066231685, 'p': 0.6882589305426767, 'r': 0.8496593077132734, 'f1': 0.7604898516783763, 'p+': 0.6796926745264273, 'r+': 0.8390842191332788, 'f1_with_ner': 0.7510245901639344}
--------------------------
Test result of saves/gsap/pruned_ner/2025-02-04/ent_pred_test.json
{'ner_p': 0.7384639948906275, 'ner_r': 0.7938551321661518, 'ner_f1': 0.7651584084705103, 'p': 0.3897032534858777, 'r': 0.4185867895545315, 'f1': 0.4036289576004443, 'p+': 0.3321415802645692, 'r+': 0.3567588325652842, 'f1_with_ner': 0.344010368450287}

In [ ]:
doc = random.choice(docs)

In [43]:
# get positional entities and relations
doc.keys()

dict_keys(['sentences', 'clusters', 'doc_tokens', 'doc_token_spans', 'ner', 'relations', 'doc_id', 'predicted_ner', 'predicted_ner_proba', 'predicted_rel'])

In [ ]:
10047_2005_06182.txt	our model	3223	3232	3210	3211

In [228]:
print(len(doc["doc_token_spans"]))
doc["doc_token_spans"][::-1]

3238

[[3264, 3265],
 [3257, 3264],
 [3254, 3256],
 [3244, 3253],
 [3241, 3243],
 [3237, 3240],
 [3231, 3236],
 [3345, 3346],
 [3337, 3345],
 [3330, 3336],
 [3326, 3329],
 [3323, 3325],
 [3317, 3322],
 [3307, 3316],
 [3303, 3306],
 [3298, 3302],
 [3294, 3297],
 [3292, 3293],
 [3283, 3292],
 [3273, 3282],
 [3269, 3272],
 [3266, 3268],
 [3254, 3265],
 [3245, 3253],
 [3237, 3244],
 [3233, 3236],
 [3227, 3232],
 [3223, 3226],
 [3218, 3222],
 [3210, 3217],
 [3207, 3209],
 [3375, 3376],
 [3369, 3375],
 [3364, 3368],
 [3354, 3363],
 [3350, 3353],
 [3347, 3349],
 [3333, 3346],
 [3327, 3332],
 [3323, 3326],
 [3316, 3322],
 [3304, 3315],
 [3296, 3303],
 [3287, 3295],
 [3281, 3286],
 [3279, 3280],
 [3273, 3278],
 [3269, 3272],
 [3265, 3268],
 [3253, 3264],
 [3249, 3252],
 [3244, 3248],
 [3235, 3243],
 [3231, 3234],
 [3226, 3230],
 [3213, 3225],
 [3206, 3212],
 [3197, 3205],
 [3188, 3196],
 [3185, 3187],
 [3183, 3184],
 [3176, 3183],
 [3436, 3437],
 [3435, 3436],
 [3433, 3435],
 [3432, 3433],
 [3419, 3431],
 [3407, 3418],
 [3404, 3406],
 [3399, 3404],
 [3395, 3398],
 [3391, 3394],
 [3384, 3390],
 [3380, 3383],
 [3377, 3379],
 [3361, 3376],
 [3356, 3360],
 [3351, 3355],
 [3342, 3350],
 [3339, 3341],
 [3337, 3338],
 [3329, 3337],
 [3323, 3328],
 [3320, 3322],
 [3307, 3319],
 [3303, 3306],
 [3295, 3302],
 [3284, 3294],
 [3282, 3283],
 [3278, 3281],
 [3271, 3277],
 [3266, 3270],
 [3253, 3265],
 [3251, 3252],
 [3247, 3251],
 [3245, 3246],
 [3241, 3245],
 [3233, 3240],
 [3229, 3232],
 [3219, 3228],
 [3215, 3218],
 [3203, 3214],
 [3200, 3202],
 [3194, 3199],
 [3185, 3193],
 [3181, 3184],
 [3178, 3180],
 [3168, 3177],
 [3159, 3167],
 [3158, 3159],
 [3155, 3158],
 [3154, 3155],
 [3147, 3154],
 [3143, 3146],
 [3138, 3142],
 [3132, 3137],
 [3129, 3131],
 [3127, 3128],
 [3119, 3127],
 [3300, 3301],
 [3297, 3300],
 [3296, 3297],
 [3292, 3296],
 [3289, 3291],
 [3287, 3289],
 [3282, 3286],
 [3276, 3281],
 [3274, 3275],
 [3262, 3274],
 [3253, 3261],
 [3245, 3252],
 [3239, 3244],
 [3234, 3238],
 [3230, 3233],
 [3228, 3229],
 [3218, 3228],
 [3204, 3217],
 [3196, 3203],
 [3193, 3195],
 [3187, 3192],
 [3184, 3186],
 [3177, 3183],
 [3175, 3176],
 [3172, 3174],
 [3162, 3171],
 [3153, 3161],
 [3142, 3152],
 [3138, 3141],
 [3131, 3137],
 [3129, 3130],
 [3127, 3129],
 [3126, 3127],
 [3120, 3125],
 [3114, 3119],
 [3113, 3114],
 [3105, 3113],
 [3101, 3104],
 [3096, 3100],
 [3088, 3095],
 [3085, 3087],
 [3080, 3084],
 [3079, 3080],
 [3078, 3079],
 [3074, 3077],
 [3175, 3176],
 [3163, 3175],
 [3161, 3162],
 [3156, 3161],
 [3152, 3155],
 [3148, 3151],
 [3144, 3147],
 [3140, 3143],
 [3139, 3140],
 [3135, 3139],
 [3132, 3134],
 [3130, 3132],
 [3126, 3129],
 [3118, 3125],
 [3113, 3117],
 [3109, 3112],
 [3105, 3108],
 [3101, 3104],
 [3100, 3101],
 [3096, 3100],
 [3093, 3095],
 [3091, 3093],
 [3087, 3090],
 [3084, 3086],
 [3079, 3083],
 [3078, 3079],
 [3077, 3078],
 [3072, 3076],
 [3067, 3071],
 [3056, 3066],
 [3046, 3055],
 [3042, 3045],
 [3069, 3070],
 [3061, 3069],
 [3058, 3060],
 [3055, 3057],
 [3047, 3054],
 [3038, 3046],
 [3035, 3037],
 [3232, 3233],
 [3217, 3232],
 [3210, 3216],
 [3206, 3209],
 [3201, 3205],
 [3196, 3200],
 [3192, 3195],
 [3181, 3191],
 [3172, 3180],
 [3163, 3171],
 [3150, 3162],
 [3144, 3149],
 [3135, 3143],
 [3131, 3134],
 [3126, 3130],
 [3117, 3125],
 [3111, 3116],
 [3109, 3110],
 [3099, 3109],
 [3089, 3098],
 [3085, 3088],
 [3077, 3084],
 [3069, 3076],
 [3059, 3068],
 [3051, 3058],
 [3039, 3050],
 [3027, 3038],
 [3015, 3026],
 [3013, 3014],
 [3007, 3012],
 [3004, 3006],
 [3207, 3208],
 [3206, 3207],
 [3204, 3206],
 [3202, 3203],
 [3200, 3202],
 [3199, 3200],
 [3190, 3198],
 [3181, 3189],
 [3177, 3180],
 [3175, 3176],
 [3173, 3175],
 [3171, 3172],
 [3169, 3171],
 [3168, 3169],
 [3159, 3167],
 [3155, 3158],
 [3150, 3154],
 [3144, 3149],
 [3139, 3143],
 [3133, 3138],
 [3131, 3132],
 [3123, 3131],
 [3113, 3122],
 [3110, 3112],
 [3103, 3109],
 [3098, 3102],
 [3085, 3097],
 [3081, 3084],
 [3080, 3081],
 [3079, 3080],
 [3075, 3078],
 [3062, 3074],
 [3051, 3061],
 [3048, 3050],
 [3043, 3048],
 [3034, 3042],
 [3030, 3033],
 [3019, 3029],
 [3016, 3018],
 [3011, 3015],
 [3004, 3010],
 [2999, 3003],
 [2989, 2998],
 [2985, 2988],
 [2976, 2984],
 [2970, 2975],
 [2966, 2969],
 [2964, 2965],
 [2958, 2964],
 [2956, 2957],
 [2953, 2955],
 [3083, 3084],
 [3082, 3083],
 [3080, 3082],
 [3079, 3080],
 [3071, 3078],
 [3063, 3070],
 [3053, 3062],
 [3050, 3052],
 [3041, 3049],
 [3035, 3040],
 [3030, 3034],
 [3017, 3029],
 [3010, 3016],
 [3001, 3009],
 [2991, 3000],
 [2988, 2990],
 [2979, 2987],
 [2976, 2978],
 [2973, 2975],
 [2968, 2972],
 [2963, 2967],
 [2957, 2962],
 [2953, 2956],
 [2944, 2952],
 [2941, 2943],
 [2939, 2940],
 [2926, 2939],
 [3065, 3066],
 [3057, 3065],
 [3050, 3056],
 [3046, 3049],
 [3043, 3045],
 [3032, 3042],
 [3028, 3031],
 [3019, 3027],
 [3011, 3018],
 [3008, 3010],
 [3000, 3007],
 [2996, 2999],
 [2987, 2995],
 [2976, 2986],
 [2972, 2975],
 [2964, 2971],
 [2960, 2963],
 [2955, 2959],
 [2949, 2954],
 [2945, 2948],
 [2940, 2944],
 [2937, 2939],
 [2931, 2936],
 [2923, 2930],
 [2916, 2922],
 [2912, 2915],
 [2909, 2911],
 [2901, 2908],
 [2897, 2900],
 [3043, 3044],
 [3036, 3043],
 [3026, 3035],
 [3022, 3025],
 [3019, 3021],
 [3010, 3018],
 [2994, 3009],
 [2986, 2993],
 [2983, 2985],
 [2973, 2982],
 [2967, 2972],
 [2965, 2966],
 [2961, 2964],
 [2955, 2960],
 [2953, 2954],
 [2943, 2953],
 [2936, 2942],
 [2926, 2935],
 [2920, 2925],
 [2919, 2920],
 [2917, 2919],
 [2913, 2916],
 [2909, 2912],
 [2900, 2908],
 [2894, 2899],
 [2892, 2893],
 [2881, 2891],
 [2878, 2880],
 [2876, 2877],
 [2869, 2876],
 [2866, 2868],
 [3032, 3033],
 [3029, 3032],
 [3023, 3028],
 [3020, 3022],
 [3014, 3019],
 [3011, 3013],
 [3006, 3010],
 [2997, 3005],
 [2991, 2996],
 [2985, 2990],
 [2984, 2985],
 [2981, 2984],
 [2977, 2980],
 [2970, 2976],
 [2968, 2969],
 [2963, 2968],
 [2960, 2962],
 [2954, 2959],
 [2941, 2953],
 [2940, 2941],
 [2935, 2940],
 [2933, 2934],
 [2922, 2932],
 [2918, 2921],
 [2913, 2917],
 [2901, 2912],
 [2899, 2900],
 [2887, 2899],
 [2884, 2886],
 [2883, 2884],
 [2878, 2882],
 [2867, 2877],
 [2863, 2866],
 [2860, 2862],
 [2849, 2859],
 [2846, 2848],
 [2843, 2845],
 [2838, 2842],
 [2829, 2837],
 [2826, 2828],
 [3017, 3018],
 [3016, 3017],
 [3014, 3016],
 [3012, 3013],
 [3010, 3012],
 [3009, 3010],
 [3000, 3008],
 [2994, 2999],
 [2990, 2993],
 [2987, 2989],
 [2981, 2986],
 [2974, 2980],
 [2970, 2973],
 [2967, 2969],
 [2961, 2966],
 [2958, 2960],
 [2954, 2957],
 [2948, 2953],
 [2942, 2947],
 [2938, 2941],
 [2936, 2937],
 [2925, 2936],
 [2917, 2924],
 [2909, 2916],
 [2904, 2908],
 [2893, 2903],
 [2884, 2892],
 [2881, 2883],
 [2877, 2880],
 [2871, 2876],
 [2867, 2870],
 [2859, 2866],
 [2852, 2858],
 [2849, 2851],
 [2840, 2848],
 [2833, 2839],
 [2831, 2832],
 [2826, 2830],
 [2823, 2825],
 [2814, 2822],
 [2808, 2813],
 [2804, 2807],
 [2794, 2803],
 [2790, 2793],
 [2786, 2789],
 [2780, 2785],
 [2883, 2884],
 [2876, 2883],
 [2869, 2875],
 [2859, 2868],
 [2855, 2858],
 [2852, 2854],
 [2845, 2851],
 [2834, 2844],
 [2830, 2833],
 [2825, 2829],
 [2814, 2824],
 [2808, 2813],
 [2803, 2807],
 [2799, 2802],
 [2796, 2798],
 [2781, 2795],
 [2776, 2780],
 [2771, 2775],
 [2763, 2770],
 [2760, 2762],
 [2939, 2940],
 [2931, 2939],
 [2928, 2930],
 [2923, 2927],
 [2917, 2922],
 [2911, 2916],
 [2907, 2910],
 [2903, 2906],
 [2897, 2902],
 [2885, 2896],
 [2878, 2884],
 [2872, 2877],
 [2866, 2871],
 [2861, 2865],
 [2857, 2860],
 [2852, 2856],
 [2846, 2851],
 [2838, 2845],
 [2836, 2837],
 [2834, 2835],
 [2831, 2834],
 [2828, 2830],
 [2820, 2827],
 [2816, 2819],
 [2812, 2815],
 [2810, 2811],
 [2804, 2810],
 [2799, 2803],
 [2795, 2798],
 [2792, 2794],
 [2778, 2791],
 [2768, 2777],
 [2763, 2767],
 [2758, 2762],
 [2750, 2757],
 [2747, 2749],
 [2742, 2746],
 [2737, 2741],
 [2732, 2736],
 [2724, 2731],
 [2721, 2723],
 [2718, 2720],
 [2898, 2899],
 [2892, 2898],
 [2880, 2891],
 [2876, 2879],
 [2871, 2875],
 [2861, 2870],
 [2855, 2860],
 [2851, 2854],
 [2845, 2850],
 [2838, 2844],
 [2834, 2837],
 [2826, 2833],
 [2813, 2825],
 [2806, 2812],
 [2801, 2805],
 [2791, 2800],
 [2785, 2790],
 [2781, 2784],
 [2779, 2780],
 [2766, 2779],
 [2760, 2765],
 [2757, 2759],
 [2748, 2756],
 [2740, 2747],
 [2738, 2739],
 [2730, 2737],
 [2724, 2729],
 [2720, 2723],
 [2716, 2719],
 [2712, 2715],
 [2707, 2711],
 [2703, 2706],
 [2698, 2702],
 [2696, 2697],
 [2695, 2696],
 [2693, 2694],
 [2690, 2693],
 [2687, 2689],
 [2681, 2686],
 [2678, 2680],
 [2821, 2822],
 [2814, 2821],
 [2810, 2813],
 [2808, 2809],
 [2796, 2808],
 [2795, 2796],
 [2794, 2795],
 [2792, 2793],
 [2780, 2792],
 [2778, 2779],
 [2765, 2778],
 [2764, 2765],
 [2763, 2764],
 [2761, 2762],
 [2755, 2761],
 [2754, 2755],
 [2753, 2754],
 [2751, 2752],
 [2746, 2751],
 [2740, 2745],
 [2736, 2739],
 [2731, 2735],
 [2725, 2730],
 [2717, 2724],
 [2709, 2716],
 [2703, 2708],
 [2698, 2702],
 [2694, 2697],
 [2680, 2693],
 [2673, 2679],
 [2668, 2672],
 [2658, 2667],
 [2652, 2657],
 [2650, 2651],
 [2643, 2649],
 [3093, 3094],
 [3089, 3093],
 [3082, 3088],
 [3079, 3081],
 [3078, 3079],
 [3077, 3078],
 [3073, 3076],
 [3070, 3072],
 [3056, 3069],
 [3050, 3055],
 [3046, 3049],
 [3043, 3045],
 [3041, 3042],
 [3033, 3040],
 [3025, 3032],
 [3021, 3024],
 [3016, 3020],
 [3013, 3015],
 [3011, 3012],
 [2998, 3010],
 [2991, 2997],
 [2988, 2990],
 [2984, 2987],
 [2980, 2983],
 [2973, 2979],
 [2970, 2972],
 [2968, 2969],
 [2955, 2968],
 [2949, 2954],
 [2944, 2948],
 [2934, 2943],
 [2931, 2933],
 [2920, 2930],
 [2913, 2919],
 [2903, 2912],
 [2900, 2902],
 [2895, 2900],
 [2891, 2894],
 [2887, 2890],
 [2884, 2886],
 [2872, 2883],
 [2868, 2871],
 [2861, 2867],
 [2858, 2860],
 [2852, 2857],
 [2849, 2851],
 [2846, 2848],
 [2842, 2845],
 [2840, 2841],
 [2838, 2839],
 [2835, 2838],
 [2832, 2834],
 [2822, 2831],
 [2819, 2821],
 [2816, 2818],
 [2814, 2815],
 [2802, 2814],
 [2795, 2801],
 [2794, 2795],
 [2789, 2794],
 [2778, 2788],
 [2775, 2777],
 [2771, 2774],
 [2767, 2770],
 [2764, 2766],
 [2757, 2763],
 [2752, 2756],
 [2742, 2751],
 [2738, 2741],
 [2731, 2737],
 [2728, 2730],
 [2725, 2727],
 [2719, 2724],
 [2711, 2718],
 [2707, 2710],
 [2704, 2706],
 [2694, 2703],
 [2689, 2693],
 [2685, 2688],
 [2683, 2684],
 [2678, 2683],
 [2670, 2677],
 [2666, 2669],
 [2659, 2665],
 [2651, 2658],
 [2648, 2650],
 [2639, 2647],
 [2629, 2638],
 [2625, 2628],
 [2612, 2624],
 [2602, 2611],
 [2599, 2601],
 [2588, 2598],
 [2582, 2587],
 [2579, 2581],
 [2570, 2578],
 [2566, 2569],
 [2561, 2565],
 [2554, 2560],
 [2551, 2553],
 [2542, 2550],
 [2635, 2636],
 [2634, 2635],
 [2632, 2634],
 [2630, 2631],
 [2628, 2630],
 [2627, 2628],
 [2620, 2626],
 [2611, 2619],
 [2610, 2611],
 [2603, 2610],
 [2597, 2602],
 [2592, 2596],
 [2587, 2591],
 [2579, 2586],
 [2576, 2578],
 [2570, 2575],
 [2564, 2569],
 [2560, 2563],
 [2555, 2559],
 [2546, 2554],
 [2542, 2545],
 [2538, 2541],
 [2534, 2537],
 [2531, 2533],
 [2528, 2530],
 [2526, 2527],
 [2515, 2526],
 [2658, 2659],
 [2655, 2658],
 [2654, 2655],
 [2650, 2654],
 [2648, 2649],
 [2646, 2648],
 [2637, 2645],
 [2628, 2636],
 [2622, 2627],
 [2620, 2621],
 [2617, 2620],
 [2616, 2617],
 [2612, 2616],
 [2610, 2611],
 [2608, 2610],
 [2606, 2607],
 [2600, 2605],
 [2594, 2599],
 [2583, 2593],
 [2580, 2582],
 [2573, 2579],
 [2567, 2572],
 [2563, 2566],
 [2558, 2562],
 [2556, 2557],
 [2551, 2556],
 [2548, 2550],
 [2541, 2547],
 [2539, 2540],
 [2536, 2538],
 [2531, 2535],
 [2522, 2530],
 [2516, 2521],
 [2510, 2515],
 [2509, 2510],
 [2501, 2509],
 [2497, 2500],
 [2490, 2496],
 [2488, 2489],
 [2487, 2488],
 [2485, 2486],
 [2482, 2485],
 [2479, 2481],
 [2473, 2478],
 [2470, 2472],
 [2548, 2549],
 [2543, 2548],
 [2533, 2542],
 [2529, 2532],
 [2524, 2528],
 [2518, 2523],
 [2515, 2517],
 [2507, 2514],
 [2497, 2506],
 [2483, 2496],
 [2475, 2482],
 [2472, 2474],
 [2463, 2471],
 [2459, 2462],
 [2455, 2458],
 [2596, 2597],
 [2595, 2596],
 [2593, 2595],
 [2592, 2593],
 [2580, 2591],
 [2566, 2579],
 [2560, 2565],
 [2556, 2559],
 [2551, 2555],
 [2546, 2550],
 [2541, 2545],
 [2534, 2540],
 [2524, 2533],
 [2513, 2523],
 [2507, 2512],
 [2506, 2507],
 [2505, 2506],
 [2501, 2504],
 [2499, 2500],
 [2493, 2499],
 [2487, 2492],
 [2479, 2486],
 [2475, 2478],
 [2468, 2474],
 [2464, 2467],
 [2459, 2463],
 [2454, 2458],
 [2451, 2453],
 [2446, 2450],
 [2445, 2446],
 [2444, 2445],
 [2435, 2443],
 [2431, 2434],
 [2428, 2430],
 [2420, 2427],
 [2508, 2509],
 [2507, 2508],
 [2505, 2507],
 [2503, 2504],
 [2501, 2503],
 [2499, 2500],
 [2497, 2499],
 [2496, 2497],
 [2490, 2495],
 [2484, 2489],
 [2483, 2484],
 [2475, 2483],
 [2471, 2474],
 [2466, 2470],
 [2455, 2465],
 [2441, 2454],
 [2437, 2440],
 [2424, 2436],
 [2421, 2423],
 [2416, 2421],
 [2412, 2415],
 [2400, 2411],
 [2397, 2399],
 [2605, 2606],
 [2592, 2605],
 [2589, 2591],
 [2586, 2588],
 [2575, 2585],
 [2572, 2574],
 [2566, 2571],
 [2564, 2565],
 [2556, 2564],
 [2552, 2555],
 [2539, 2551],
 [2535, 2538],
 [2531, 2534],
 [2518, 2530],
 [2511, 2517],
 [2505, 2510],
 [2500, 2504],
 [2496, 2499],
 [2494, 2495],
 [2487, 2494],
 [2484, 2486],
 [2478, 2483],
 [2472, 2477],
 [2468, 2471],
 [2463, 2467],
 [2459, 2462],
 [2450, 2458],
 [2443, 2449],
 [2441, 2442],
 [2437, 2440],
 [2428, 2436],
 [2417, 2427],
 [2413, 2416],
 [2408, 2412],
 [2398, 2407],
 [2395, 2397],
 [2391, 2394],
 [2387, 2390],
 [2385, 2386],
 [2375, 2385],
 [2369, 2374],
 [2364, 2368],
 [2361, 2363],
 [2359, 2360],
 [2352, 2359],
 [2510, 2511],
 [2498, 2510],
 [2488, 2497],
 [2482, 2487],
 [2481, 2482],
 [2474, 2481],
 [2471, 2473],
 [2469, 2470],
 [2468, 2469],
 [2467, 2468],
 [2454, 2466],
 [2446, 2453],
 [2441, 2445],
 [2439, 2440],
 [2429, 2439],
 [2421, 2428],
 [2420, 2421],
 [2411, 2420],
 [2405, 2410],
 [2402, 2404],
 [2393, 2401],
 [2384, 2392],
 [2380, 2383],
 [2377, 2379],
 [2364, 2376],
 [2355, 2363],
 [2351, 2354],
 [2345, 2350],
 [2340, 2344],
 [2334, 2339],
 [2326, 2333],
 [2320, 2325],
 [2436, 2437],
 [2433, 2436],
 [2430, 2432],
 [2424, 2429],
 [2421, 2423],
 [2419, 2420],
 [2416, 2419],
 [2415, 2416],
 [2413, 2414],
 [2411, 2413],
 [2408, 2410],
 [2406, 2407],
 [2402, 2406],
 [2401, 2402],
 [2399, 2400],
 [2397, 2399],
 [2391, 2396],
 [2388, 2390],
 [2379, 2387],
 [2376, 2378],
 [2371, 2376],
 [2366, 2370],
 [2357, 2365],
 [2354, 2356],
 [2352, 2353],
 [2346, 2352],
 [2341, 2345],
 [2333, 2340],
 [2332, 2333],
 [2329, 2332],
 [2320, 2328],
 [2315, 2319],
 [2306, 2314],
 [2297, 2305],
 [2293, 2296],
 [2284, 2292],
 [2378, 2379],
 [2377, 2378],
 [2375, 2377],
 [2373, 2374],
 [2371, 2373],
 [2370, 2371],
 [2361, 2369],
 [2357, 2360],
 [2352, 2356],
 [2339, 2351],
 [2333, 2338],
 [2329, 2332],
 [2325, 2328],
 [2323, 2324],
 [2318, 2323],
 [2313, 2317],
 [2309, 2312],
 [2303, 2308],
 [2299, 2302],
 [2290, 2298],
 [2288, 2289],
 [2286, 2288],
 [2284, 2285],
 [2282, 2284],
 [2281, 2282],
 [2272, 2280],
 [2268, 2271],
 [2263, 2267],
 [2258, 2262],
 [2254, 2257],
 [2363, 2364],
 [2353, 2363],
 [2343, 2352],
 [2339, 2342],
 [2336, 2338],
 [2334, 2335],
 [2328, 2334],
 [2324, 2327],
 [2320, 2323],
 [2316, 2319],
 [2311, 2315],
 [2307, 2310],
 [2302, 2306],
 [2297, 2301],
 [2295, 2296],
 [2287, 2295],
 ...]

In [ ]:
docs = load_docs(fn_pred)
fn_test_gt = "/home/ottowg/projects/gsap/gsap-rel/preprocessing/gsap-rel-sentence-simple/test.jsonl"
docs = load_docs(fn_test_gt, False)

In [260]:
doc = [d for d in docs if d["doc_id"] == "10047_2005_06182.txt"][0]

In [261]:
for sent_ents in doc["ner"]:
    for begin, end, label in sent_ents:
        if (begin, end) == (3210, 3211):
            print(prob, label)
            print(doc["doc_token_spans"][begin])
            print(doc["doc_token_spans"][end])

9.859976835002726e-09 MLModelGeneric
[17322, 17325]
[17326, 17331]

In [249]:
doc["doc_token_spans"][begin]

[17322, 17325]

In [250]:
doc["doc_token_spans"][end]

[17326, 17331]

In [ ]:
"/home/ottowg/projects/gsap/gsap-rel-related/HGERE/saves/gsap/HGERE/scibert/tersibcop/facencbiaf-seq512-mem400-iter3-layernorm+_attnself/ent400-rel400-lr2e-5-1e-4-bs18-ep10-eps1e

{'key': ('00001_1911_02116.txt', 5, 7), 'doc_id': '00001_1911_02116.txt', 'text': 'multilingual language models', 'begin': 105, 'end': 133, 'begin_token': 5, 'end_token': 7, 'label_gold': 'MLModelGeneric', 'is_ent': True, 'in_rel': False, 'annotator': 'test_non_null_hgere', 'prob_prune': 0.7363318800926208, 'label': 'MLModelGeneric', 'ref_id': 0}
2797

In [167]:
wi

[PosixPath('/home/ottowg/projects/gsap/gsap-rel-related/HGERE/saves/gsap/HGERE/scibert/tersibcop/facencbiaf-seq512-mem400-iter3-layernorm+_attnself/ent400-rel400-lr2e-5-1e-4-bs18-ep10-eps1e-8/hyper_gsap_scibert-2025-02-04-43/scripts'),
 PosixPath('/home/ottowg/projects/gsap/gsap-rel-related/HGERE/saves/gsap/HGERE/scibert/tersibcop/facencbiaf-seq512-mem400-iter3-layernorm+_attnself/ent400-rel400-lr2e-5-1e-4-bs18-ep10-eps1e-8/hyper_gsap_scibert-2025-02-04-43/all_spkogpu01.log'),
 PosixPath('/home/ottowg/projects/gsap/gsap-rel-related/HGERE/saves/gsap/HGERE/scibert/tersibcop/facencbiaf-seq512-mem400-iter3-layernorm+_attnself/ent400-rel400-lr2e-5-1e-4-bs18-ep10-eps1e-8/hyper_gsap_scibert-2025-02-04-43/args'),
 PosixPath('/home/ottowg/projects/gsap/gsap-rel-related/HGERE/saves/gsap/HGERE/scibert/tersibcop/facencbiaf-seq512-mem400-iter3-layernorm+_attnself/ent400-rel400-lr2e-5-1e-4-bs18-ep10-eps1e-8/hyper_gsap_scibert-2025-02-04-43/checkpoint-61680'),
 PosixPath('/home/ottowg/projects/gsap/gsap-rel-related/HGERE/saves/gsap/HGERE/scibert/tersibcop/facencbiaf-seq512-mem400-iter3-layernorm+_attnself/ent400-rel400-lr2e-5-1e-4-bs18-ep10-eps1e-8/hyper_gsap_scibert-2025-02-04-43/pred_ent_pred_test.json'),
 PosixPath('/home/ottowg/projects/gsap/gsap-rel-related/HGERE/saves/gsap/HGERE/scibert/tersibcop/facencbiaf-seq512-mem400-iter3-layernorm+_attnself/ent400-rel400-lr2e-5-1e-4-bs18-ep10-eps1e-8/hyper_gsap_scibert-2025-02-04-43/test_results.txt')]

In [ ]:
len(spans_pred)

2797

In [122]:
## Save Predictions
spans_df = pd.DataFrame(ents_pred)
f = ~spans_df.is_ent & spans_df.in_rel
spans_df[f]

,key,doc_id,text_,begin,end,begin_token,end_token,label_gold,is_ent,in_rel,prob_prune,label,id
1455,"(00001_1911_02116.txt, 4282, 4282)",00001_1911_02116.txt,Unicoder,4358,4366,4282,4282,MLModel,False,True,0.736332,NaN,1455
2513,"(00013_2104_08727.txt, 1933, 1933)",00013_2104_08727.txt,answers,1939,1946,1933,1933,DatasetGeneric,False,True,0.736332,NaN,2513
3531,"(00013_2104_08727.txt, 5042, 5049)",00013_2104_08727.txt,"short , snippet , and collection response ques...",5159,5208,5042,5049,DatasetGeneric,False,True,0.736332,NaN,3531
9030,"(00050_1406_2661.txt, 2374, 2374)",00050_1406_2661.txt,maxout,2482,2488,2374,2374,NIL,False,True,0.736332,NaN,9030
9681,"(10018_2208_04405.txt, 1648, 1648)",10018_2208_04405.txt,regression,1736,1746,1648,1648,NIL,False,True,0.736332,NaN,9681
10425,"(10018_2208_04405.txt, 4684, 4686)",10018_2208_04405.txt,the Laplacian rule,4701,4719,4684,4686,NIL,False,True,0.736332,NaN,10425
10786,"(10019_2204_02965.txt, 574, 576)",10019_2204_02965.txt,the base ResNet-50,605,623,574,576,MLModelGeneric,False,True,0.736332,NaN,10786
11352,"(10019_2204_02965.txt, 2465, 2468)",10019_2204_02965.txt,convolutional and dense layers,2497,2527,2465,2468,NIL,False,True,0.736332,NaN,11352
11890,"(10019_2204_02965.txt, 4464, 4466)",10019_2204_02965.txt,the torchac library,4506,4525,4464,4466,NIL,False,True,0.736332,NaN,11890
14669,"(10037_1804_05260.txt, 6706, 6707)",10037_1804_05260.txt,the perceptron,6776,6790,6706,6707,NIL,False,True,0.736332,NaN,14669
16954,"(10037_1804_05260.txt, 15012, 15017)",10037_1804_05260.txt,a bag - of - words,15095,15109,15012,15017,Method,False,True,0.736332,NaN,16954
17154,"(10037_1804_05260.txt, 15651, 15652)",10037_1804_05260.txt,the ClassiNet,15676,15689,15651,15652,NIL,False,True,0.736332,NaN,17154
17252,"(10037_1804_05260.txt, 16082, 16082)",10037_1804_05260.txt,PageRank,16177,16185,16082,16082,Method,False,True,0.736332,NaN,17252
19026,"(10040_2112_07839.txt, 4631, 4631)",10040_2112_07839.txt,Mime,4703,4707,4631,4631,NIL,False,True,0.736332,NaN,19026
19391,"(10040_2112_07839.txt, 5732, 5733)",10040_2112_07839.txt,momentum acceleration,5765,5786,5732,5733,Method,False,True,0.736332,NaN,19391
20837,"(10047_2005_06182.txt, 1220, 1225)",10047_2005_06182.txt,the un - normalized attention score,1234,1267,1220,1225,NIL,False,True,0.736332,NaN,20837
21057,"(10047_2005_06182.txt, 2031, 2032)",10047_2005_06182.txt,the encoder,2113,2124,2031,2032,MLModelGeneric,False,True,0.736332,NaN,21057

In [102]:
pd.DataFrame(rels)

                    doc_id  subject_id relation_label  object_id    id
0     00001_1911_02116.txt           1        usedFor          1     0
1     00001_1911_02116.txt           9   architecture          9     1
2     00001_1911_02116.txt           9      trainedOn          9     2
3     00001_1911_02116.txt          13    sourcedFrom         13     3
4     00001_1911_02116.txt          18    coreference         18     4
...                    ...         ...            ...        ...   ...
2792  10047_2005_06182.txt       21324       citation      21324  2792
2793  10047_2005_06182.txt       21333      trainedOn      21333  2793
2794  10047_2005_06182.txt       21333    coreference      21333  2794
2795  10047_2005_06182.txt       21338        usedFor      21338  2795
2796  10047_2005_06182.txt       21335       citation      21335  2796

[2797 rows x 5 columns]

In [41]:
#fn_docs_gt = '/home/ottowg/projects/gsap/gsap-rel-related/HGERE/saves/gsap/pruned_ner/'

In [ ]:
sent_idxs = list(range(len(doc["sentences"])))
print(len(sent_idxs))
sent_idxs_selected = []
for idx in sent_idxs:
    if doc["ner"][idx] or doc["predicted_ner"][idx]:
        sent_idxs_selected.append(idx)
print(len(sent_idxs_selected))

193
117

In [40]:
## choose random sentence
sent_idx = random.choice(sent_idxs_selected)
print(f"sentence_idx:", sent_idx)## prepare sent (incl. ents and relations)
sent = " ".join(doc["sentences"][sent_idx])
ent_dict = defaultdict(list)
for start, end, label in doc["ner"][sent_idx]:
    ent_token = []
    for token_idx in range(start, end + 1):
        token = doc["doc_tokens"][token_idx]
        ent_token.append(token)
    ent_text = " ".join(ent_token)
    ent_print = f"[{label}: '{ent_text}']"
    ent_dict[(start, end)].append(ent_print)
rels_print = []
for subj_start, subj_end, obj_start, obj_end, label in doc["relations"][sent_idx]:
    subj = ", ".join(ent_dict[(subj_start, subj_end)])
    obj = ", ".join(ent_dict[(obj_start, obj_end)])
    rel_print = f"{subj} - {label} -> {obj}"
    rels_print.append(rel_print)

pred_ent_dict = defaultdict(list)
for start, end, label in doc["predicted_ner"][sent_idx]:
    ent_token = []
    for token_idx in range(start, end + 1):
        token = doc["doc_tokens"][token_idx]
        ent_token.append(token)
    ent_text = " ".join(ent_token)
    ent_print = f"[{label}: '{ent_text}']"
    pred_ent_dict[(start, end)].append(ent_print)
pred_rels_print = []
for subj_start, subj_end, obj_start, obj_end, label in doc["predicted_rel"][sent_idx]:
    subj = ", ".join(pred_ent_dict[(subj_start, subj_end)])
    obj = ", ".join(pred_ent_dict[(obj_start, obj_end)])
    rel_print = f"{subj} - {label} -> {obj}"
    pred_rels_print.append(rel_print)

## print sentence
print(sent)
print("NER")
for ent_print in ent_dict.values():
    print("", " ".join(ent_print))
print("RELATIONS")
for rel in rels_print:
    print("", rel)
print()
print("NER predicted")
for ent_print in pred_ent_dict.values():
    print("", " ".join(ent_print))
print("RELATIONS predicted")
for rel in pred_rels_print:
    print("", rel)

sentence_idx: 22
In this work , we focus on linear stochastic networked dynamical systems , which is arguably one of the most natural settings for network identification from time series since a great class of nonlinear networked dynamical systems can be addressed via linearization about the equilibria under smallnoise regimes ( Ching and Tam 2017 ; Napoletani and Sauer 2008 ) or via appropriate embedding in higher dimensional spaces ( Lim et al . 2015 ; Mauroy and Goncalves 2016 ) .
NER
 [MLModelGeneric: 'linear stochastic networked dynamical systems']
 [DatasetGeneric: 'time series']
 [MLModelGeneric: 'nonlinear networked dynamical systems']
 [ReferenceLink: 'Ching and Tam 2017']
 [ReferenceLink: 'Napoletani and Sauer 2008']
 [ReferenceLink: 'Lim et al . 2015']
 [ReferenceLink: 'Mauroy and Goncalves 2016']
RELATIONS

NER predicted
 [DatasetGeneric: 'linear stochastic networked dynamical systems']
 [Task: 'network identification']
 [DatasetGeneric: 'time series']
 [Method: 'nonlinear networked dynamical systems']
 [ReferenceLink: 'Ching and Tam 2017']
 [ReferenceLink: 'Napoletani and Sauer 2008']
 [ReferenceLink: 'Lim et al . 2015']
 [ReferenceLink: 'Mauroy and Goncalves 2016']
RELATIONS predicted
 [DatasetGeneric: 'linear stochastic networked dynamical systems'] - appliedTo -> [Task: 'network identification']
 [DatasetGeneric: 'linear stochastic networked dynamical systems'] - isHyponymOf -> [Method: 'nonlinear networked dynamical systems']
 [DatasetGeneric: 'linear stochastic networked dynamical systems'] - citation -> [ReferenceLink: 'Ching and Tam 2017']
 [DatasetGeneric: 'linear stochastic networked dynamical systems'] - citation -> [ReferenceLink: 'Napoletani and Sauer 2008']
 [DatasetGeneric: 'linear stochastic networked dynamical systems'] - citation -> [ReferenceLink: 'Lim et al . 2015']
 [DatasetGeneric: 'linear stochastic networked dynamical systems'] - citation -> [ReferenceLink: 'Mauroy and Goncalves 2016']
 [DatasetGeneric: 'time series'] - benchmarkFor -> [Task: 'network identification']
 [Method: 'nonlinear networked dynamical systems'] - appliedTo -> [Task: 'network identification']
 [Method: 'nonlinear networked dynamical systems'] - citation -> [ReferenceLink: 'Ching and Tam 2017']
 [Method: 'nonlinear networked dynamical systems'] - citation -> [ReferenceLink: 'Napoletani and Sauer 2008']
 [Method: 'nonlinear networked dynamical systems'] - citation -> [ReferenceLink: 'Lim et al . 2015']
 [Method: 'nonlinear networked dynamical systems'] - citation -> [ReferenceLink: 'Mauroy and Goncalves 2016']